### PR TITLE
fix(editor): fix memory leaks on editor db transactions

### LINKED ISSUE #14: DB transaction left unclosed
```
...
09:10:36.239 [Finalizer] ERROR c.c.d.editor.datastore.DatabaseTx - DB transaction left unclosed, this signifies a memory leak!
...
```

### PR DESCRIPTION
**Pull request by landonreed**
A number of model classes had getters that created transactions that were never rolled back.  This
moves those into addDerivedInfo functions.

fixes #14

### CODE REVIEW

File: src/main/java/com/conveyal/datatools/editor/controllers/Base.java [hunk 1]
```diff
@@ -26,6 +26,7 @@
         mod.addSerializer(GtfsRouteType.class, new JacksonSerializers.GtfsRouteTypeSerializer());
         mod.addDeserializer(TripDirection.class, new JacksonSerializers.TripDirectionDeserializer());
         mod.addSerializer(TripDirection.class, new JacksonSerializers.TripDirectionSerializer());
+        mapper.getSerializerProvider().setNullKeySerializer(new JacksonSerializers.MyDtoNullKeySerializer());
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/Base.java]: What does this do?

File: src/main/java/com/conveyal/datatools/editor/controllers/api/AgencyController.java [hunk 2]
```diff
@@ -73,6 +76,8 @@ public static Object createAgency(Request req, Response res) {
         } catch (Exception e) {
             e.printStackTrace();
             halt(400);
+        } finally {
+            if (tx != null) tx.rollbackIfOpen();
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/AgencyController.java]: I'm curious why we use rollback in some places (AgencyController) and rollbackIfOpen in other places.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java [hunk 3]
```diff
@@ -62,54 +58,44 @@ public static Object getCalendar(Request req, Response res) {
...
+                    ServiceCalendar cal = tx.calendars.get(calendarId);
+                    Long count = tx.tripCountByPatternAndCalendar.get(new Fun.Tuple2(patternId, cal.id));
+                    if (count == null) count = 0L;
+                    ret.add(new ServiceCalendarForPattern(cal, tx.tripPatterns.get(patternId), count));
+                }
                 return ret;
             }
             else {
-                Collection<ServiceCalendar> cals = tx.calendars.values();
+                Collection<ServiceCalendar> cals = new ArrayList<>(tx.calendars.values());
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java]: It might make sense to have a comment here explaining why we're making a new list.

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java]: A comment here might be worthwhile so it's clear why we're creating a new arraylist.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java [hunk 4]
```diff
@@ -37,37 +39,32 @@ public static Object getFare(Request req, Response res) {
...
-//                    fare.addDerivedInfo(tx);
                     return fare;
                 }
             }
             else {
-                Collection<Fare> fares = tx.fares.values();
-                for (Fare fare : fares) {
-//                    fare.addDerivedInfo(tx);
-                }
+                Collection<Fare> fares = new ArrayList<>(tx.fares.values());
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java]: This should have a comment.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java [hunk 5]
```diff
@@ -140,42 +127,51 @@ public static Object updateFare(Request req, Response res) {
...
             tx.fares.put(fare.id, fare);
-
-            Object json = Base.toJson(fare, false);
-
             tx.commit();
-
-            return json;
+            return fare;
         } catch (HaltException e) {
             LOG.error("Halt encountered", e);
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java]: I see these all over the place, why are we catching and rethrowing halts?

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java]: Did I do that?

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java [hunk 6]
```diff
@@ -92,162 +77,83 @@ public static Object createFeedInfo(Request req, Response res) {
...
         } catch (Exception e) {
             e.printStackTrace();
             halt(400);
+        } finally {
+            if (gtx != null) gtx.rollbackIfOpen();
         }
         return null;
     }
 
-    public static void applyJsonToFeedInfo(EditorFeed source, String json) throws IOException {
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java]: Glad to see this function go, there has to be a better way.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java [hunk 7]
```diff
@@ -92,162 +77,83 @@ public static Object createFeedInfo(Request req, Response res) {
...
-            if(entry.getKey().equals("feedLang")) {
-                source.feedLang = entry.getValue().asText();
-            }
+    /**
+     * Delete NOT ONLY feed info, but also entirely delete the record of the feed in the editor database.
+     * @param req
+     * @param res
+     * @return
+     */
+    public static Object deleteFeedInfo(Request req, Response res) {
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java]: Should this function be called something that makes it more clear what it does in case future @mattwigway doesn't read the javadocs and assumes it deletes feed info? Something like `wipeAllTraceOfFeedFromDatabaseIHopeYouMakeBackups`?

File: src/main/java/com/conveyal/datatools/editor/controllers/api/RouteController.java [hunk 8]
```diff
@@ -28,82 +32,70 @@
...
                 route.addDerivedInfo(tx);
 
-                json = Base.toJson(route, false);
-
-//                return route;
+                return route;
             }
             else {
-                Route[] ret = tx.routes.values().toArray(new Route[tx.routes.size()]);
+                Set<Route> ret = new HashSet<>(tx.routes.values());
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/RouteController.java]: The set works fine, but what was wrong with what we had before? toArray will create an array divorced from the underlying database.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/ScheduleExceptionController.java [hunk 9]
```diff
@@ -198,12 +191,12 @@ public static Object deleteScheduleException (Request req, Response res) {
         if (feedId == null) {
             halt(400);
         }
-
         FeedTx tx = VersionedDataStore.getFeedTx(feedId);
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/ScheduleExceptionController.java]: Technically we should put a try-catch around this as well.

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/ScheduleExceptionController.java]: (so that it gets rolled back if an exception is thrown in this block)

File: src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java [hunk 10]
```diff
@@ -48,57 +49,73 @@
...
-    public int getNumberOfTrips () {
-        FeedTx tx = VersionedDataStore.getFeedTx(this.feedId);
-        Collection<Trip> trips = tx.getTripsByPattern(this.id);
-        return trips == null ? 0 : trips.size();
+    // give the UI a little information about the content of this trip pattern
+    public transient Long numberOfTrips;
+    public transient Map<String, Long> tripCountByCalendar;
+
+
+    @JsonProperty("numberOfTrips")
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: We _might_ be able to do this by putting and `@JsonInclude` annotation on the transient field.

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: (i.e. I'm not sure if it will work)

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: (but it would be cleaner)

File: src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java [hunk 11]
```diff
@@ -48,57 +49,73 @@
...
-                ret[i] = GeoUtils.geometyFactory.createLineString(new Coordinate[] {stop, snapped});
-            }
-
-            return ret;
-        } finally {
-            tx.rollback();
-        }
-
-    }
+//    @JsonProperty("stopConnections")
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: Man, do we not show the little lines connecting stops to shapes in the UI anymore? :cry:

File: src/main/java/com/conveyal/datatools/editor/controllers/Base.java (hunk 1 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/Base.java]: Ignores null keys in maps in case they somehow get in (e.g., corrupt MapDB).

File: src/main/java/com/conveyal/datatools/editor/controllers/api/AgencyController.java (hunk 2 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/AgencyController.java]: I was using `rollback` in functions handling `get` requests, but maybe `rollbackIfOpen` is always the way to go.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java (hunk 3 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java]: good point.

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java (hunk 5 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FareController.java]: No, not you.  I was running into issues where halts were getting caught by the `catch (Exception e) {}` clause.  See this comment: https://github.com/perwendel/spark/blob/e2854295f7c484671ce69bff7ec37fcb0c413a32/src/main/java/spark/Service.java#L562-L564

File: src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java (hunk 7 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/FeedInfoController.java]: Good call...

File: src/main/java/com/conveyal/datatools/editor/controllers/api/RouteController.java (hunk 8 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/RouteController.java]: I think when I was tearing my hair out trying to figure out where the leaks were, at one point it seemed like this was fixing the issue (I think it was a false negative).

File: src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java (hunk 10 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: Unfortunately not :(

File: src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java (hunk 3 above)
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/controllers/api/CalendarController.java]: Not to be nitpicky, but comments starting with `/**` are Javadoc comments (although since it's not above a class/function/field def or at the top of the file it shouldn't be much of a problem, whereas `//` and `/*` are standard comments. I generally only use `//` comments in code, because then you can comment out a whole block of code with the `/*` style without wondering if there are other `/*` comments in there to throw a wrench in things.

File: src/main/java/com/conveyal/datatools/editor/jobs/ProcessGtfsSnapshotExport.java [hunk 12]
```diff
@@ -208,26 +207,11 @@ public void run() {
...
-                            if (trip.wheelchairBoarding.equals(AttributeAvailabilityType.AVAILABLE))
-                                gtfsTrip.wheelchair_accessible = 1;
-
-                            else if (trip.wheelchairBoarding.equals(AttributeAvailabilityType.UNAVAILABLE))
-                                gtfsTrip.wheelchair_accessible = 2;
-
-                            else
-                                gtfsTrip.wheelchair_accessible = 0;
-
+                            gtfsTrip.wheelchair_accessible = trip.wheelchairBoarding.toGtfs();
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/jobs/ProcessGtfsSnapshotExport.java]: Nice.

File: src/main/java/com/conveyal/datatools/editor/models/transit/Stop.java [hunk 13]
```diff
@@ -116,11 +116,13 @@ public static Stop fromJson(@JsonProperty("lat") double lat, @JsonProperty("lon"
         ret.stop_desc = stopDesc;
         ret.stop_lat = location.getY();
         ret.stop_lon = location.getX();
+        // TODO gtfs-lib value needs to be int
+//        ret.wheelchair_boarding = wheelchairBoarding.toGtfs();
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/Stop.java]: Why is this commented out?

Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/Stop.java]: Ah, the GTFS-lib type is string. Yeah we should change that (in fact there's a comment in GTFS Lib to that effect) but for the time being should we just cast the int to a string?

File: src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java [hunk 14]
```diff
@@ -47,7 +45,7 @@
 
     public TripDirection patternDirection;
 
-    public List<TripPatternStop> patternStops = new ArrayList<TripPatternStop>();
+    public List<TripPatternStop> patternStops = new ArrayList<>();
 
     // give the UI a little information about the content of this trip pattern
     public transient Long numberOfTrips;
```
Comment (mattwigway) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: Why is this a long? Would there ever be more than 2^31 trips on a pattern? I think that would even make the code below crash, since map.size returns an int.

File: src/main/java/com/conveyal/datatools/editor/models/transit/Stop.java (hunk 13 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/models/transit/Stop.java]: Yea, let's cast for now.

File: src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java (hunk 14 above)
Comment (landonreed) [inline src/main/java/com/conveyal/datatools/editor/models/transit/TripPattern.java]: Ah, was just mimicking the same field type in ServiceCalendar.  Definitely doesn't need to be a long.
